development:
  adapter: postgresql
  database: discoverbps_upgrade
  encoding: utf8
  host: localhost
  username: postgres
  password: postgres
  port: 5432
  pool: 5
  timeout: 5000
  <% if RUBY_PLATFORM =~ /darwin/ %>gssencmode: disable<% end %>  # This will only be evaluated on macOS

test:
  adapter: postgresql
  database: discoverbps_test_upgrade
  encoding: utf8
  host: localhost
  username: postgres
  password: postgres
  port: 5432
  pool: 5
  timeout: 5000
  <% if RUBY_PLATFORM =~ /darwin/ %>gssencmode: disable<% end %>  # This will only be evaluated on macOS


# production:
#   adapter: postgresql
#   database: discoverbps
#   encoding: unicode
#   host: localhost
#   port: 5432
#   pool: 5
#   timeout: 5000